// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvmtHz4jafQom0jR8j0DO4RgRcspKa0l8',
    appId: '1:699902163185:android:4139977ed89164737a5150',
    messagingSenderId: '699902163185',
    projectId: 'iztradingv1',
    databaseURL: 'https://iztradingv1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iztradingv1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4EEqsSf2mOaT6wdFAxe0goeLveNT0RU8',
    appId: '1:699902163185:ios:520469cc3f03e8137a5150',
    messagingSenderId: '699902163185',
    projectId: 'iztradingv1',
    databaseURL: 'https://iztradingv1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iztradingv1.appspot.com',
    androidClientId: '699902163185-66rq7ug7jchg45e52cocbvnmsv3otjck.apps.googleusercontent.com',
    iosClientId: '699902163185-9fh8of4roou79etqb9qhtgaselm6fc7e.apps.googleusercontent.com',
    iosBundleId: 'com.bqh04.ezTrading',
  );
}
